#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Dec  2 12:58:37 2019

@author: riopescador
"""

import pandas as pd

A = {'Student':['Ice Bear','Panda','Grizzly'],
        'Math':[80,95,79]}

B = {'Student':['Ice Bear','Panda','Grizzly'],
        'Electronics':[85,81,83]}

C = {'Student':['Ice Bear','Panda','Grizzly'],
        'GEAS':[90,79,93]}

D = {'Student':['Ice Bear','Panda','Grizzly'],
        'ESAT':[93,89,88]}

E = pd.DataFrame(A, columns=['Student','Math'])
F = pd.DataFrame(B, columns=['Student','Electronics'])
G = pd.DataFrame(C, columns=['Student','GEAS'])
H = pd.DataFrame(D, columns=['Student','ESAT'])

a = pd.merge(E, F, how='left', on='Student')
b = pd.merge(a, G, how='left', on='Student')
c = pd.merge(b, H, how='left', on='Student')